# Generated by Django 3.0.7 on 2020-06-09 08:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('date_current', models.DateField(default=datetime.date.today)),
                ('date_end', models.DateField()),
                ('time_1', models.TimeField()),
                ('time_2', models.TimeField(blank=True, null=True)),
                ('time_3', models.TimeField(blank=True, null=True)),
                ('time_4', models.TimeField(blank=True, null=True)),
                ('medicine_image', models.ImageField(default='default.jpeg', upload_to='reminders')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
