# Generated by Django 3.0.7 on 2020-06-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='medicine_image',
            field=models.ImageField(default='default.jpg', upload_to='reminders'),
        ),
    ]
