# Generated by Django 3.0.7 on 2020-06-10 09:32

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20200609_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=300)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
                ('systolic', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('diastolic', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(250)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
